/**
 * memo.js — build a Markdown procurement decision memo from application state.
 * Pure function (no I/O, no AI) so it is reproducible and unit-testable, and can
 * be rendered by the server (GET /api/export) or offline by a script.
 */
import { scoreVendors, computeMetrics } from "./scoring.js";

export function fmtINR(n) {
  const v = Math.round(Number(n) || 0);
  const s = Math.abs(v).toString();
  const last3 = s.slice(-3);
  const rest = s.slice(0, -3);
  const grouped = rest ? rest.replace(/\B(?=(\d{2})+(?!\d))/g, ",") + "," + last3 : last3;
  return `${v < 0 ? "-" : ""}INR ${grouped}`;
}

export function buildMemo(state) {
  const scoring = scoreVendors(state);
  const metrics = computeMetrics(state);
  const rec = scoring.rows.find((r) => r.id === scoring.recommendedId);
  const latest = state.decisions[state.decisions.length - 1];
  const L = [];

  L.push(`# Procurement Recommendation Memo`, ``);
  L.push(`**Company:** ${state.scenario.company}  `);
  L.push(`**Category:** ${state.scenario.category} (${state.scenario.quantity} units)  `);
  L.push(`**Prepared with:** ProcureWise (decision support — no orders placed by the system)  `, ``);
  L.push(`## Requirement`, state.scenario.requirementSummary, ``);

  L.push(`## Comparison (deterministic scoring)`);
  L.push(`| Rank | Vendor | Score /100 | Fleet TCO | Per-unit | Compliant |`);
  L.push(`|---|---|---|---|---|---|`);
  for (const r of scoring.rows) {
    L.push(`| ${r.rank} | ${r.name} | ${r.totalScore} | ${fmtINR(r.tco)} | ${fmtINR(r.tcoPerUnit)} | ${r.compliant ? "Yes" : "No — " + r.complianceGaps.join(", ")} |`);
  }
  L.push(``, `**Criteria weights:** ${scoring.weightsUsed.map((w) => `${w.label} ${w.weight}%`).join(", ")}.`, ``);

  if (rec) {
    L.push(`## System recommendation`);
    L.push(`**${rec.name}** — highest-scoring compliant vendor (score ${rec.totalScore}/100).`);
    if (metrics) {
      L.push(`- Fleet TCO: ${fmtINR(rec.tco)} (${fmtINR(rec.tcoPerUnit)}/unit)`);
      L.push(`- Estimated saving vs budget: ${fmtINR(metrics.savingsVsBudget)} (${metrics.savingsVsBudgetPct}%)`);
      L.push(`- Mandatory compliance: passed`);
    }
    L.push(``);
  }

  L.push(`## Human decision`);
  if (latest) {
    L.push(`- **Decision:** ${latest.action.toUpperCase()}${latest.wasOverride ? " (override of system recommendation)" : ""}`);
    L.push(`- **Awarded to:** ${latest.vendorName || "—"}`);
    L.push(`- **Approver:** ${latest.decidedBy}`);
    L.push(`- **Rationale:** ${latest.reason || "—"}`);
    L.push(`- **Timestamp:** ${latest.timestamp}`);
  } else {
    L.push(`- No human decision has been recorded yet. The recommendation above is advisory only.`);
  }
  L.push(``, `---`);
  L.push(`_Generated by ProcureWise. AI is used to explain and communicate; all monetary figures come from the deterministic scoring engine. No purchase order is issued by the system._`);
  return L.join("\n");
}
